[build]
  command = "npm run build:client"
  functions = "netlify/functions"
  publish = "dist/spa"


[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"

[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"

# [[redirects]]
#   from = "/chat_api/*"
#   to = "http://216.244.94.213:8080/chat_api/:splat"
#   status = 200
#   force = true

# ORINAI CHAT PORT 8080
[[redirects]]
  from = "/agents"
  to = "https://orinai-dashboard-proxy-1056582462205.asia-southeast1.run.app/ai_chat/agents"
  status = 200
  force = true

[[redirects]]
  from = "/agents/*"
  to = "https://orinai-dashboard-proxy-1056582462205.asia-southeast1.run.app/ai_chat/agents/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/whatsapp/number"
  to = "https://orinai-dashboard-proxy-1056582462205.asia-southeast1.run.app/ai_chat/whatsapp/number"
  status = 200
  force = true

[[redirects]]
  from = "/whatsapp/number/*"
  to = "https://orinai-dashboard-proxy-1056582462205.asia-southeast1.run.app/ai_chat/whatsapp/number/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/tools"
  to = "https://orinai-dashboard-proxy-1056582462205.asia-southeast1.run.app/ai_chat/tools"
  status = 200
  force = true

[[redirects]]
  from = "/tools/*"
  to = "https://orinai-dashboard-proxy-1056582462205.asia-southeast1.run.app/ai_chat/tools/:splat"
  status = 200
  force = true

# WA REPORT PORT 8000
[[redirects]]
  from = "/notification_setting"
  to = "https://orinai-dashboard-proxy-1056582462205.asia-southeast1.run.app/wa_report/notification_setting"
  status = 200
  force = true

[[redirects]]
  from = "/notification_setting/*"
  to = "https://orinai-dashboard-proxy-1056582462205.asia-southeast1.run.app/wa_report/notification_setting/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/send_message"
  to = "https://orinai-dashboard-proxy-1056582462205.asia-southeast1.run.app/wa_report/whatsapp/send_message"
  status = 200
  force = true

[[redirects]]
  from = "/send_message/*"
  to = "https://orinai-dashboard-proxy-1056582462205.asia-southeast1.run.app/wa_report/whatsapp/send_message/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/whatsapp/disable_agent"
  to = "https://orinai-dashboard-proxy-1056582462205.asia-southeast1.run.app/wa_report/whatsapp/disable_agent"
  status = 200
  force = true

[[redirects]]
  from = "/whatsapp/disable_agent/*"
  to = "https://orinai-dashboard-proxy-1056582462205.asia-southeast1.run.app/wa_report/whatsapp/disable_agent/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/whatsapp/contacts"
  to = "https://orinai-dashboard-proxy-1056582462205.asia-southeast1.run.app/wa_report/whatsapp/contacts"
  status = 200
  force = true

[[redirects]]
  from = "/whatsapp/contacts/*"
  to = "https://orinai-dashboard-proxy-1056582462205.asia-southeast1.run.app/wa_report/whatsapp/contacts/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/whatsapp/chat_history"
  to = "https://orinai-dashboard-proxy-1056582462205.asia-southeast1.run.app/wa_report/whatsapp/chat_history"
  status = 200
  force = true

[[redirects]]
  from = "/whatsapp/chat_history/*"
  to = "https://orinai-dashboard-proxy-1056582462205.asia-southeast1.run.app/wa_report/whatsapp/chat_history/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/whatsapp/profile"
  to = "https://orinai-dashboard-proxy-1056582462205.asia-southeast1.run.app/wa_report/whatsapp/profile"
  status = 200
  force = true

[[redirects]]
  from = "/whatsapp/profile/*"
  to = "https://orinai-dashboard-proxy-1056582462205.asia-southeast1.run.app/wa_report/whatsapp/profile/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/whatsapp/dummy_notification"
  to = "https://orinai-dashboard-proxy-1056582462205.asia-southeast1.run.app/wa_report/whatsapp/dummy_notification"
  status = 200
  force = true

[[redirects]]
  from = "/whatsapp/dummy_notification/*"
  to = "https://orinai-dashboard-proxy-1056582462205.asia-southeast1.run.app/wa_report/whatsapp/dummy_notification/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/whatsapp/phone_to_lid"
  to = "https://orinai-dashboard-proxy-1056582462205.asia-southeast1.run.app/wa_report/whatsapp/phone_to_lid"
  status = 200
  force = true

[[redirects]]
  from = "/whatsapp/phone_to_lid/*"
  to = "https://orinai-dashboard-proxy-1056582462205.asia-southeast1.run.app/wa_report/whatsapp/phone_to_lid/:splat"
  status = 200
  force = true
