[build]
  command = "npm run build:client"
  functions = "netlify/functions"
  publish = "dist/spa"


[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
  
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"

# [[redirects]]
#   from = "/chat_api/*"
#   to = "http://216.244.94.213:8080/chat_api/:splat"
#   status = 200
#   force = true

[[redirects]]
  from = "/agents/*"
  to = "http://216.244.94.213:8080/agents/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/whatsapp/number/*"
  to = "http://216.244.94.213:8080/whatsapp/number/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/tools/*"
  to = "http://216.244.94.213:8080/tools/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/whatsapp/contacts/*"
  to = "http://216.244.94.213:8000/whatsapp/contacts/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/whatsapp/chat_history/*"
  to = "http://216.244.94.213:8000/whatsapp/chat_history/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/whatsapp/profile/*"
  to = "http://216.244.94.213:8000/whatsapp/profile/:splat"
  status = 200
  force = true
